#!/usr/bin/env bash
#Displays numbers 1 to 100 in a list.
# If number is multiple of 3 and 5 display "FizzBuzz"
# If number is multiple of 3, display "Fizz"
# If number is multiple of 5, display "Buzz"
# Else display the number

for num in {1..100}
do
	if ((num % 15) == 0)
	then
		echo "FizzBuzz"
	elif ((num % 3) == 0)
	then
		echo "Fizz"
	elif ((num % 5) == 0)
	then
		echo "Buzz"
	else
		echo "$num"
	fi
done
