#!/usr/bin/env bash
# Script displays numbers 1 to 20
# displays 4 and then "bad luck from China" at the 4th loop
# displays 9 and then "bad luck from Japan" at the 9th loop
# displays 17 and then "bad luck from Italy" at the 17th loop
x=1 
while [ $x -le 20 ]; 
do
	echo "$x"
	case $x in
		"4") echo "bad luck from China";;
		"9") echo "bad luck from Japan";;
		"17") echo "bad luck from Italy";;
	esac
	((x++))
done
